# RforMassSpectrometry

The aim of the RforMassSpectrometry is to provide efficient,
thoroughly documented, tested and flexible R software for the analysis
and interpretation of high throughput mass spectrometry assays,
including proteomics and metabolomics experiments. The project
formalises the longtime collaborative development efforts of its core
members under the RforMassSpectrometry organisation to facilitate
dissemination and accessibility of their work.


## Software

The RforMassSpectrometry packages are available as git repositories
under the RforMassSpectrometry organisation. This is the main
development and collaboration platform of the project. Once the
packages have reached a satisfactory level of maturity and stability,
they are submitted to the [Bioconductor](http://www.bioconductor.org)
project to integrate with existing, broader infrastructure for high
throughput biology data.

The RforMassSpectrometry initiative aims at co-developing and
maintaining interoperable software to tackle a wide range of needs in
computational mass spectrometry using R. The goal is not to address
all needs, or those that we feel we can't offer a improvement for. In
the light of these overall goals, the interoperablity principle is an
important one, as we strive to provide a set of software that work
together efficiently, rather that maximising the number of packages.


## Questions

For questions about specific software or their usage, please refer to
the specific software's issue page, or use the [Bioconductor support
site](http://support.bioconductor.org/). For questions about the
RforMassSpectrometry initiative, please ... either issues in the web
page repository, or get a dedicated email address?

## Members

Current core members include the developers of the `r BiocStyle::Biocpkg("MSnbase")`,
from which this initiative rose.

- [Laurent Gatto](https://github.com/lgatto), UCLouvain, Belgium
- [Sebastien Gibb](https://github.com/sgibb)
- [Johannes Rainer](https://github.com/jorainer)

## Contributions
